name: "Deploy main"

on:
  push:
    # branches:
    #   - main

concurrency:
  group: push_main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: rustup component add rustfmt
      - name: "cargo fmt"
        run: cargo fmt --all -- --check

      - run: rustup component add clippy
      - name: "cargo clippy"
        run: cargo clippy -- -D warnings

      - name: "cargo build"
        run: cargo build --verbose

      - name: "cargo test"
        run: cargo test --verbose
