name: "Deploy main"

on:
  push:
    # branches:
    #   - main

concurrency:
  group: push_main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lint_test:
    name: Build all targets and runs tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -yq --no-install-suggests --no-install-recommends install libx11-dev libxi-dev libgl1-mesa-dev gcc-mingw-w64 libasound2-dev

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy -- -D warnings

      - name: cargo build
        run: cargo build

      - name: cargo test
        run: cargo test
